; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#include "installer.iss"
[Setup]
OutputBaseFilename=quantom_for_quantaxis_x86_v{#MyAppVersion}

[Files]
Source: "D:\Workspace\quantom\vendor\quantaxisbackend-x86.exe"; DestDir: "{app}"; DestName: "quantaxisbackend.exe"; Flags: ignoreversion 
